image:
  file: .gitpod.Dockerfile

tasks:
  - init: sdk use java 16.0.1.hs-adpt
    command: echo "replace whit something that should run on every start."

ports:
  # used by virtual desktop and vnc, supports JavaFX
  - port: 6080
