image: maven:latest
stages:
  - lint
  - compile
  - test

lint:commit:
  stage: lint
  script:
    - echo "${CI_COMMIT_MESSAGE}" | npx commitlint

compile:
  stage: compile
  script:
    - cd pmdb
    - mvn compile

test:
  stage: test
  script:
    - cd pmdb
    - mvn test



